# Generated by Django 2.2 on 2020-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='conf_file',
            field=models.FileField(default=None, upload_to='', verbose_name='配置文件'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip',
            field=models.CharField(max_length=32, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='交换机名称'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='position',
            field=models.CharField(max_length=256, verbose_name='交换机位置'),
        ),
    ]
