# Generated by Django 2.2 on 2020-01-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200105_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='conf_file',
        ),
    ]
