# Generated by Django 2.2 on 2020-01-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_switch_conf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='conf_file',
            field=models.FileField(default=None, upload_to='conf_file', verbose_name='配置文件'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='描述'),
        ),
    ]
