# Generated by Django 2.2 on 2020-01-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200106_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='conf_file',
            field=models.FileField(default='None', null=True, upload_to='conf_file', verbose_name='配置文件'),
        ),
    ]
