# Generated by Django 2.2 on 2020-01-07 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20200106_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='conf_file',
        ),
        migrations.AddField(
            model_name='switch',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/'),
            preserve_default=False,
        ),
    ]
