# Generated by Django 2.2 on 2020-01-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_switch_conf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='conf_file',
        ),
    ]
